In [1]:
import pandas as pd

# 📁 기본 경로
base_path = r"C:\Users\user\Desktop\빅데이터 분석 부트캠프\파이널프로젝트\train"

# 📄 파일 불러오기
df1 = pd.read_csv(f"{base_path}\\03.승인매출 정보(train).csv")
df2 = pd.read_csv(f"{base_path}\\3.승인매출2_train.csv")
df3 = pd.read_csv(f"{base_path}\\청구잔액정보_병합(train).csv")
df4 = pd.read_csv(f"{base_path}\\Train회원정보2_요약.csv")

# 📌 기준년월 문자형(str)으로 통일
for df in [df1, df2, df3, df4]:
    if '기준년월' in df.columns:
        df['기준년월'] = df['기준년월'].astype(str)

# 🔗 병합 순서 (모두 ID + 기준년월 기준)
merged = pd.merge(df1, df2, on=['ID', '기준년월'], how='outer')
merged = pd.merge(merged, df3, on=['ID', '기준년월'], how='outer')
merged = pd.merge(merged, df4, on=['ID', '기준년월'], how='outer')

# ✅ 결과 확인
print("✅ 최종 병합 데이터 shape:", merged.shape)
print(merged.head())

✅ 최종 병합 데이터 shape: (2400000, 20)
             ID  _2순위업종_이용금액  최대이용금액_일시불_R12M  납부_기타이용금액  쇼핑_편의점_이용금액  \
0  TRAIN_000000         1408             4906         44            0
1  TRAIN_000000         1523             5350         40            0
2  TRAIN_000000         1462             6009         44            0
3  TRAIN_000000         1367             5901         48            0
4  TRAIN_000000         1356             6257         44            0

   _2순위교통업종_이용금액  최대이용금액_CA_R12M  교통_정비이용금액    기준년월  할부금액_무이자_3M_R12M  \
0            105           11710          0  201807              1314
1              0           11738          0  201808              1124
2              0           11747          0  201809               989
3              0           11942          0  201810               954
4              0           12116          0  201811               976

   이용개월수_온라인_R6M  연속유실적개월수_기본_24M_카드      이용금액대  청구금액_R6M  평잔_일시불_해외_6M  \
0              1                  13  01.100만원+     88693             0
1              1                  13  01.100만원+    119419             0
2              1                  17  01.100만원+    132269             0
3              1                  17  01.100만원+     92304             0
4              0                  17  01.100만원+     97254             0

   잔액_일시불_B2M  평잔_일시불_6M  이용카드수_신용체크  _1순위카드이용건수 Segment
0        1083       2440           1          26       D
1         736       2697           1          23       D
2         997       2735           1          27       D
3         697       2562           1          26       D
4         607       2431           1          26       D

In [2]:
merged

,ID,_2순위업종_이용금액,최대이용금액_일시불_R12M,납부_기타이용금액,쇼핑_편의점_이용금액,_2순위교통업종_이용금액,최대이용금액_CA_R12M,교통_정비이용금액,기준년월,할부금액_무이자_3M_R12M,이용개월수_온라인_R6M,연속유실적개월수_기본_24M_카드,이용금액대,청구금액_R6M,평잔_일시불_해외_6M,잔액_일시불_B2M,평잔_일시불_6M,이용카드수_신용체크,_1순위카드이용건수,Segment
0,TRAIN_000000,1408,4906,44,0,105,11710,0,201807,1314,1,13,01.100만원+,88693,0,1083,2440,1,26,D
1,TRAIN_000000,1523,5350,40,0,0,11738,0,201808,1124,1,13,01.100만원+,119419,0,736,2697,1,23,D
2,TRAIN_000000,1462,6009,44,0,0,11747,0,201809,989,1,17,01.100만원+,132269,0,997,2735,1,27,D
3,TRAIN_000000,1367,5901,48,0,0,11942,0,201810,954,1,17,01.100만원+,92304,0,697,2562,1,26,D
4,TRAIN_000000,1356,6257,44,0,0,12116,0,201811,976,0,17,01.100만원+,97254,0,607,2431,1,26,D
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2399995,TRAIN_399999,2168,5760,0,0,0,0,0,201808,18391,0,2,03.30만원+,28912,0,0,1600,2,-2,E
2399996,TRAIN_399999,2687,6233,0,0,0,0,0,201809,18477,0,5,02.50만원+,42577,0,998,1742,2,-1,E
2399997,TRAIN_399999,2447,6091,0,0,0,0,0,201810,18640,0,5,03.30만원+,23976,0,814,1410,2,-2,E
2399998,TRAIN_399999,2647,4624,0,0,0,0,0,201811,15516,0,5,04.10만원+,26946,0,1485,993,2,-2,E
2399999,TRAIN_399999,926,4593,0,0,0,0,0,201812,13847,0,5,04.10만원+,19948,0,972,1053,2,-2,E

In [3]:
# 💾 CSV로 저장
merged.to_csv(f"{base_path}\\train.csv", index=False, encoding='utf-8-sig')

In [4]:
# 1. 리스트 형태로 보기
print(merged.columns.tolist())

['ID', '_2순위업종_이용금액', '최대이용금액_일시불_R12M', '납부_기타이용금액', '쇼핑_편의점_이용금액', '_2순위교통업종_이용금액', '최대이용금액_CA_R12M', '교통_정비이용금액', '기준년월', '할부금액_무이자_3M_R12M', '이용개월수_온라인_R6M', '연속유실적개월수_기본_24M_카드', '이용금액대', '청구금액_R6M', '평잔_일시불_해외_6M', '잔액_일시불_B2M', '평잔_일시불_6M', '이용카드수_신용체크', '_1순위카드이용건수', 'Segment']